# Generated by Django 5.0 on 2024-02-22 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
