# Generated by Django 5.0 on 2024-02-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_patient_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_available',
        ),
    ]
